deployments:
  pipelines:
    dockerimage: ubuntu:trusty
    pipelines:
      - website:
          dockerimage: ubuntu:xenial
          build_steps:
            - apt-get update && apt-get install -y git curl
            - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --allow-unauthenticated postgresql postgresql-contrib libpq-dev pgadmin3
            - cd /code/mysite
            - service postgresql start
            - su postgres bash -c "psql -c 'create database test_db;'"
            - su postgres bash -c "psql -c "\""alter user postgres with password 'postgres';"\"""
            - apt-get install -y software-properties-common python-software-properties
            - add-apt-repository ppa:deadsnakes/ppa -y
            - apt-get update && apt-get install -y python3.6 python-setuptools python3.6-dev
            - curl https://bootstrap.pypa.io/get-pip.py | python3.6
            - pip3 install --upgrade setuptools
            - pip3 install -r ./requirements.txt
          scripts:
            - POSTGRES_HOST=localhost POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres POSTGRES_DB=test_db coverage run ./manage.py test --verbosity 2 && coverage report --fail-under=30
      - lua:
          build_steps:
            - apt-get update && apt-get -y install sudo
            - useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo
            - 'echo "docker ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
            - su docker
            - sudo apt-get update && sudo apt-get install -y luajit luarocks git build-essential
            - sudo luarocks install luafilesystem
            - sudo luarocks install luassert 1.7.11-0
            - sudo luarocks install busted 2.0.rc13-0
            - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
            - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            - sudo apt-get -y install software-properties-common
            - sudo touch /etc/apt/sources.list.d/openresty.list
            - echo "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/openresty.list
            - sudo apt-get update -o Dir::Etc::sourcelist=/etc/apt/sources.list.d/openresty.list
            - sudo apt-get install -y openresty
            - sudo luarocks install lua-resty-busted
          scripts:
            - busted -v
